name: test-workflow

on: [push]

jobs: 
  test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '18'
      - run: node --version
      - run: npm init -y
      - run: node app.js


